CREATE DATABASE VIRTUAL_ROLL_CALL;
USE VIRTUAL_ROLL_CALL;

CREATE TABLE OFFICERS (userID INT NOT NULL, First_Name VARCHAR (20) NOT NULL, Last_Name VARCHAR(20) NOT NULL, Username VARCHAR(20) NOT NULL, Password VARCHAR(40) NOT NULL, Role VARCHAR(40) NOT NULL, Active TINYINT(1) NOT NULL );
ALTER TABLE OFFICERS ADD PRIMARY KEY(userID);
MODIFY userID INT UNSIGNED AUTO_INCREMENT;
ALTER TABLE OFFICERS ADD UNIQUE (Username);
ALTER TABLES OFFICERS ALTER Active SET DEFAULT 1;
INSERT INTO OFFICERS(First_Name, Last_Name, Username, Password, Role, Active) VALUES('Jason', 'Cohen', 'jcohen001', 'jason123' 'Administrator', 1);
INSERT INTO OFFICERS(First_Name, Last_Name, Username, Password, Role, Active) VALUES('Frank', 'Alvarado', 'falva001', 'frank123' 'Supervisor', 1);
INSERT INTO OFFICERS(First_Name, Last_Name, Username, Password, Role, Active) VALUES('Test', 'Tester', 'test001', 'test1233' 'Officer', 1);

CREATE TABLE CATEGORIES (category_ID INT, Category_Name VARCHAR(50) NOT NULL);
ALTER TABLE CATEGORIES ADD PRIMARY KEY(category_ID);
ALTER TABLE CATEGORIES MODIFY category_ID INT UNSIGNED AUTO_INCREMENT;
ALTER TABLE CATEGORIES ADD UNIQUE (Category_Name);
INSERT INTO CATEGORIES(Category_Name) VALUES('Message From Chief');
INSERT INTO CATEGORIES(Category_Name) VALUES('Shift Line Up');
INSERT INTO CATEGORIES(Category_Name) VALUES('Watch Orders');
INSERT INTO CATEGORIES(Category_Name) VALUES('BOLO');
INSERT INTO CATEGORIES(Category_Name) VALUES('Training');
INSERT INTO CATEGORIES(Category_Name) VALUES('Internal Memos');

CREATE TABLE DOCUMENTS(document_ID INT, Document_Name VARCHAR(50) NOT NULL, Category_ID INT UNSIGNED NOT NULL, Upload_Date DATE NOT NULL, Pinned TINYINT(1) NOT NULL, Uploaded_By VARCHAR (255) NOT NULL, Upload_Name VARCHAR (255) NOT NULL);
ALTER TABLE DOCUMENTS ADD PRIMARY KEY(document_ID);
ALTER TABLE DOCUMENTS MODIFY document_ID INT UNSIGNED AUTO_INCREMENT;
ALTER TABLE DOCUMENTS ADD UNIQUE (Document_Name);
ALTER TABLE DOCUMENTS ADD FOREIGN KEY(Category_ID) REFERENCES CATEGORIES(category_ID) ON DELETE CASCADE;

CREATE TABLE SETTINGS (Application_Name VARCHAR(255) NOT NULL, Department_Name VARCHAR(255) NOT NULL); 
ALTER TABLE SETTINGS ADD PRIMARY KEY(Application_Name, Department_Name);
INSERT INTO SETTINGS(Application_Name, Department_Name) VALUES('Virtual Roll Call', 'Pinecrest Police Department');